version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    healthcheck:
      test: curl -sS http://nginx | grep -c works > /dev/null
      interval: 6s
      retries: 5
      start_period: 2s
      timeout: 10s
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  php:
    build:
      context: .
      dockerfile: image/Dockerfile
    volumes:
      - ./www:/var/www